apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dump-request-admission
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-dump-request-admission
